### ISSUE TITLE
long press using repeater or else

### ISSUE THREAD

**Issue by MichaelIndra** [matthijsthoolen/blaster#1]
I want to ask you. previously, if you use google API to transmit? then you have to use the repeater as well as a TV remote control where you hold the volume up, it automatically increases the volume of your TV hardware. if ever, can you give me an example? By the way, i use google API

thanks in advance. I apologize if my speech and inappropriate language

**Comment by matthijsthoolen** [comment]
No at the moment I made this app the Google API did not exist. I used an API written for samsung.

**Comment by MichaelIndra** [comment]
ok so google can't send signal repeater. thank you for your advice.
